openapi: 3.0.1
info:
  title: Verendus Vehicle Inspection Service
  description: A REST API for vehicle inspections
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Vehicle
    description: vehicle inspection service endpoint
  - name: Report
    description: report service endpoint
  - name: Auth
    description: Authentication service endpoint
paths:
  /vehicle:
    get:
      tags:
        - Vehicle
      description: Fetch all vehicle inpections
      summary: Get all vehicle
      responses:
        200:
          description: Return the list of the all vehicle inpections
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Vehicle"
        4XX:
          description: Vehicle not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Vehicle not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      tags:
        - Vehicle
      description: Upload a vehicle inspection file
      summary: Upload a vehicle file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                reportFile:
                  type: string
                  format: binary
      responses:
        201:
          description: Return the result of the file processing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReportUploadRes"
        4XX:
          description: Process not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Error in the vehicles list parsing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /vehicle/identity/{identity}:
    get:
      tags:
        - Vehicle
      summary: Find by Identity Number
      parameters:
        - name: identity
          in: path
          description: The identity number of the vehicle to retrieve
          required: true
          schema:
            type: string
      description: retrieve a vehicle information by its identity number
      responses:
        200:
          description: Return the vehicle information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vehicle"
        4XX:
          description: Vehicle not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Vehicle not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /vehicle/chassis/{chassisNumber}:
    get:
      tags:
        - Vehicle
      summary: Find by Chassis Number
      parameters:
        - name: chassisNumber
          in: path
          description: The chassis number number of the vehicle to retrieve
          required: true
          schema:
            type: string
      description: retrieve a vehicle information by its chassis number
      responses:
        200:
          description: Return the vehicle information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vehicle"
        4XX:
          description: Vehicle not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Vehicle not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /report/new/in-days/{days}:
    get:
      tags:
        - Report
      parameters:
        - name: days
          in: path
          description: The days ago from which you need the report
          required: true
          schema:
            type: string
      summary: New added vehicle from days ago
      description: Retrieve a list of chassis number and inspection dates for all vehicle inpections
      responses:
        200:
          description: Return a list of vehicle consist of a chassis number and inspection dates
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewVehicleByDay"
        4XX:
          description: Report not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Report not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /report:
    get:
      tags:
        - Report
      summary: A report consisting of Chassis Number and Inspection Dates
      description: Retrieve a list of chassis number and inspection dates for all vehicle inpections
      responses:
        200:
          description: Return a list of vehicle consist of a chassis number and inspection dates
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InspectionByChassisNumberBundle"
        4XX:
          description: Report not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Report not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Vehicle:
      type: object
      properties:
        identity:
          type: string
          example: TN14780
        chassisNumber:
          type: string
          example: JTEGG32M500015704
        modelYear:
          type: number
          example: 2004
        typeApprovalNo:
          type: number
          example: 52750082004
        privatelyImported:
          type: boolean
          example: true
        color:
          type: string
          example: SVART
        registration:
          type: object
          properties:
            firstRegistration:
              type: number
              example: 20090127
            latestRegistration:
              type: number
              example: 20130628
            monthlyRegistration:
              type: number
              example: 1206
            dateOfDeregistration:
              type: number
              example: 0
        inspection:
          type: object
          properties:
            latestInspectionDate:
              type: number
              example: 20170103
            nextInspectionDate:
              type: number
              example: 20181031
    ReportUploadRes:
      type: object
      properties:
        vehicles:
          type: array
          items:
            $ref: "#/components/schemas/UpdateLog"
        totalAdded:
          type: number
          example: 0
        totalUpdated:
          type: number
          example: 0
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ParseError"
        processTime:
          type: number
          example: 0.03
    Error:
      type: object
      properties:
        error:
          type: string
          example: ""
    UpdateLog:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/Vehicle"
        isNew:
          type: number
        diff:
          type: array
          items:
            $ref: "#/components/schemas/DiffResult"
    DiffResult:
      type: object
      properties:
        name:
          type: string
          example: ""
        oldValue:
          type: string
          example: ""
        sub:
          type: array
          items:
            $ref: "#/components/schemas/DiffResult"
    ParseError:
      type: object
      properties:
        line:
          type: number
          example: 3
        text:
          type: string
    InspectionByChassisNumberBundle:
      title: InspectionByChassisNumberBundle
      type: object
      properties:
        chassisNumber:
          type: string
          example: JTEGG32M500015704
        inspection:
          type: object
          properties:
            latestInspectionDate:
              type: number
              example: 20170103
            nextInspectionDate:
              type: number
              example: 20181031
    NewVehicleByDay:
      type: array
      items:
        type: object
        properties:
          _id:
            type: object
            properties:
              day:
                type: string
                example: 12
              month:
                type: string
                example: 2
          count:
            type: number
            example: 25
